# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    paths: 
      - 'MonetizationCodeSample/OutlookWebAddInWeb/**'
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.4.0
      with:
        dotnet-version: 2.1.80
        
    - name: Build with dotnet
      run: dotnet build MonetizationCodeSample/OutlookWebAddInWeb/OutlookWebAddInWeb.csproj --configuration Release

    - name: Publish with dotnet
      run: dotnet publish MonetizationCodeSample/OutlookWebAddInWeb/OutlookWebAddInWeb.csproj --configuration Release -o ${{env.DOTNET_ROOT}}/OutlookWebAddInWeb
       
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v1
      with: 
        app-name: meocontosomonetizationoutlookaddin # Replace with your app name
        publish-profile: ${{ secrets.PublishProfile }} # Define secret variable in repository settings as per action documentation
        package: ${{env.DOTNET_ROOT}}/OutlookWebAddInWeb    
